### ISSUE TITLE
[Bug] Multiple references

### ISSUE THREAD

**Issue by nadjet** [facebookresearch/vizseq#16]
When having multiple references (attached [muti_refs.zip](https://github.com/facebookresearch/vizseq/files/3833503/muti_refs.zip)), I cannot configure metric BLEU (but I can configure GLEU). I get a 500 internal server error. 

This does not happen with a single reference (see attached [single_ref.zip](https://github.com/facebookresearch/vizseq/files/3833505/single_ref.zip)).

**Comment by kahne** [comment]
Hi @nadjet , thank you very much for reporting the issue! I made a fix in #17. Can you pull the latest code from github and reinstall VizSeq:
```
pip uninstall vizseq
git clone https://github.com/facebookresearch/vizseq
cd vizseq
pip install -e .
```

The fix will be included in `0.1.10` release as well, which will come out very soon. I will send you a notice once it's available.

**Comment by kahne** [comment]
@nadjet  `0.1.10` has been released. To upgrade, you may want to do
```bash
pip install --upgrade vizseq
```

**Comment by nadjet** [comment]
It works now. Thank you for fixing this.
