### ISSUE TITLE
🐛 AttributeError: 'VizSeqLogger' object has no attribute 'set_console_mode'

### ISSUE THREAD

**Issue by Colanim** [facebookresearch/vizseq#2]
# 🐛 Bug

When trying to run the webapp with the example data, I have this error :

> AttributeError: 'VizSeqLogger' object has no attribute 'set_console_mode'

## To reproduce

Follow README instructions : download example data and run :

`python -m vizseq.server --port 9001 --data-root ./examples/data`

**Stack trace/error message**
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/me/workspace/vizseq/vizseq/server.py", line 14, in <module>
    logger.set_console_mode(enable=True)
AttributeError: 'VizSeqLogger' object has no attribute 'set_console_mode'
```

## Expected Behavior
The code run normally.

## System information
- VizSeq Version : **0.1.2**
- Python version : **3.6.8**
- Operating system : **Ubuntu 16.04**

**Comment by kahne** [comment]
Thanks for reporting! I should be fixed by #3 now.
