### ISSUE TITLE
[Question] Calculated BLEU score

### ISSUE THREAD

**Issue by Tojens** [facebookresearch/vizseq#23]
Hi :)

The tool returns a BLEU score for the machine translation and runs great in general, but I am not sure if the BLEU score represents the sentence level or corpus level? I haven't been able to gather anything conclusive from the sacreBLEU implementation, so I am hoping you can help me with this :)

Best regards,
Tobias

**Comment by Tojens** [comment]
Also for some reason when calculating NIST it returns a score of 0.0 even though all the other scores are much higher.

![NIST](https://user-images.githubusercontent.com/44861928/69885540-e6f35300-12dd-11ea-9b63-91b6863e56f2.png)

Any idea what might be going wrong?

**Comment by kahne** [comment]
Hi @Tojens , sorry for late reply during Thanksgiving. Here is the [documentation](https://facebookresearch.github.io/vizseq/docs/getting_started/scorer_example) for scorers. Basically, it supports both corpus-level BLEU score as well as sentence-level BLEU scores. For the Jupyter Notebook interface, the one shown in your screenshot is for corpus-level one. The one shown together with the examples (`vizseq.view_examples()`) are sentence-level ones.

Yeah 0.0 NIST score seems a bit weird. Do you mind sharing the data you are using for me to replicate? Thanks!

**Comment by kahne** [comment]
I will close this for now. Please feel free to open a new one if you have other questions.
