### ISSUE TITLE
🐛 Uncaught exception GET

### ISSUE THREAD

**Issue by Colanim** [facebookresearch/vizseq#4]
# 🐛 Bug

When trying to run the webapp with the example data, I have this error :

> Uncaught exception GET

## To reproduce

Follow README instructions : download example data and run :

`python -m vizseq.server --port 9001 --data-root ./examples/data`

The server starts fine, but when accessing the webapp at `localhost:9001`, I can only see `500: Internal Server Error`.

**Stack trace/error message**
```
INFO - 11/04/19 10:36:39 - 0:00:00 - Application Started
You can navigate to http://localhost:9001
ERROR - 11/04/19 10:36:42 - 0:00:03 - Uncaught exception GET / (192.168.0.30)
                                      HTTPServerRequest(protocol='http', host='192.168.0.231:9001', method='GET', uri='/', version='HTTP/1.1', remote_ip='192.168.0.30')
ERROR - 11/04/19 10:36:42 - 0:00:03 - 500 GET / (192.168.0.30) 1.18ms
```

## Expected Behavior
The webapp run normally.

## System information
- VizSeq Version : **0.1.2**
- Python version : **3.6.8**
- Operating system : **Ubuntu 16.04**

**Comment by Colanim** [comment]
I ran the app with debug mode (`python -m vizseq.server --port 9001 --data-root ./examples/data --debug`)

and when I accessed the webapp it gave me this Traceback :

>Traceback (most recent call last):
  File "/home/remondn/.venv/presum/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/remondn/workspace/vizseq/vizseq/server.py", line 82, in get
    VizSeqWebView.get_enum_tasks_and_names_and_enum_models(args.data_root)
  File "/home/remondn/workspace/vizseq/vizseq/_view/web_view.py", line 81, in get_enum_tasks_and_names_and_enum_models
    d for d in os.listdir(data_root)
FileNotFoundError: [Errno 2] No such file or directory: './examples/data'

It's because the data was downloaded in `./data/` and not `./examples/data/`. Running the server again with the right path :

`python -m vizseq.server --port 9001 --data-root ./data`

works perfectly 😃 

---

You might want to update README and change the `data-root` path, by default `get_example_data.sh` download the data to `./data` and not `./examples/data`.

**Comment by kahne** [comment]
Thanks for reporting this! I will fix the unzipping path in `get_example_data.sh`.
